import type {
  AgentAdapter,
  SendMessageParams,
  AgentMetadata,
  Capability,
  TaskParams,
  TaskResult,
  ThinkingState,
  StreamChunk,
} from './types'

// ─── Mock response templates ──────────────────────────────────────────────────

const MOCK_RESPONSES = [
  `Great question — let me think through that for Pinnacle's marketing strategy.

For The Pinnacle Companies, content strategy should always anchor to the brand promise: precision, warmth, and mountain authenticity. Whether we're writing for Pinnacle Mountain Homes, The Collective Design, or The Collective Architecture, every piece should feel like it was crafted by someone who actually cares about the client's experience — not generated by a committee.

My recommendation for this quarter: focus the content calendar on three pillars — client story spotlights, behind-the-design features, and educational SEO content targeting high-intent searches in the Park City and Treasure Valley markets. The SEO content alone should drive a meaningful uptick in organic visibility within 60–90 days if we're consistent. Want me to draft a full content calendar, or start with keyword research for one of the markets?`,

  `Here's what I'm seeing across your current campaigns.

The highest-performing content this month has been the project reveal posts on Instagram — specifically the Collective Architecture features with natural lighting photography. They're outperforming static graphic posts by about 3.2x on engagement rate. That's a strong signal: your audience responds to authenticity and craft over polish.

For the upcoming Pinnacle Mountain Homes spring campaign, I'd lean into that insight. Lead with real photography from completed builds, pair it with short-form video walkthroughs, and anchor the messaging around the idea of "built for the life you actually live." We can run that across Instagram, LinkedIn for the design crowd, and targeted Google Display for in-market buyers in the Mountain West. Ready to build out the full campaign brief?`,

  `Let me pull together the SEO picture for you.

The Collective Design is ranking well for "interior design Park City" and adjacent terms, but there's a significant gap in the architecture space. "Modern mountain architecture Utah" and "custom home architect Sun Valley" are high-intent keywords with relatively low competition — and right now we're not appearing in the top 20 for either. That's a solvable problem with three to four well-structured landing pages and a consistent internal linking strategy.

On the technical side, Core Web Vitals are solid across all Pinnacle properties — we're in the green on LCP and CLS, though mobile FID could use some attention on the homes site. I'd prioritize the content gap first since the ROI timeline is more predictable. Want me to outline a 90-day SEO sprint plan?`,
]

// ─────────────────────────────────────────────────────────────────────────────

export class MockAdapter implements AgentAdapter {
  private delayMs: number

  constructor(config?: { delayMs?: number }) {
    this.delayMs = config?.delayMs ?? 75
  }

  // ─── sendMessage ────────────────────────────────────────────────────────────

  async sendMessage(params: SendMessageParams): Promise<ReadableStream<StreamChunk>> {
    const delayMs = this.delayMs

    // Pick a response based on message content for slight variety
    const responseIndex =
      params.message.toLowerCase().includes('seo') ||
      params.message.toLowerCase().includes('keyword')
        ? 2
        : params.message.toLowerCase().includes('campaign') ||
            params.message.toLowerCase().includes('social')
          ? 1
          : 0

    const responseText = MOCK_RESPONSES[responseIndex]
    const words = responseText.split(' ')

    return new ReadableStream<StreamChunk>({
      async start(controller) {
        // 1. Thinking event
        controller.enqueue({
          type: 'thinking',
          state: 'thinking',
          detail: 'Analyzing Pinnacle marketing context...',
        })

        await sleep(400)

        // 2. Word-by-word content deltas
        for (let i = 0; i < words.length; i++) {
          const word = words[i]
          const isLast = i === words.length - 1
          const delta = isLast ? word : word + ' '

          controller.enqueue({ type: 'content_delta', delta })

          // Vary delay slightly for realism (50–100ms per word)
          await sleep(delayMs + Math.floor(Math.random() * 50))
        }

        // 3. Message end
        controller.enqueue({
          type: 'message_end',
          usage: {
            input_tokens: Math.floor(params.message.split(' ').length * 1.3),
            output_tokens: words.length,
          },
        })

        controller.close()
      },
    })
  }

  // ─── getAgentMetadata ────────────────────────────────────────────────────────

  async getAgentMetadata(agentId: string): Promise<AgentMetadata> {
    return {
      agentId,
      name: 'Friday (Mock)',
      description:
        "The Pinnacle Companies' marketing intelligence agent — running in mock mode.",
      version: '0.0.1-mock',
      capabilities: await this.getCapabilities(agentId),
    }
  }

  // ─── getCapabilities ─────────────────────────────────────────────────────────

  async getCapabilities(_agentId: string): Promise<Capability[]> {
    return [
      { id: 'content', name: 'Content', description: 'Blog posts, copy, and editing' },
      { id: 'seo', name: 'SEO', description: 'Keyword research, rankings, and technical SEO' },
      { id: 'social', name: 'Social', description: 'Instagram, LinkedIn, and scheduling' },
      { id: 'analytics', name: 'Analytics', description: 'GA4, reporting, and insights' },
    ]
  }

  // ─── runTask ─────────────────────────────────────────────────────────────────

  async runTask(params: TaskParams): Promise<TaskResult> {
    await sleep(200)
    return {
      taskId: `mock-task-${Date.now()}`,
      status: 'queued',
      message: `Mock task "${params.taskType}" queued successfully`,
    }
  }

  // ─── getThinkingState ────────────────────────────────────────────────────────

  async getThinkingState(_agentId: string): Promise<ThinkingState> {
    return { state: 'idle' }
  }

  // ─── ping ────────────────────────────────────────────────────────────────────

  async ping(): Promise<boolean> {
    return true
  }
}

// ─── Utility ─────────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}
